/**
 * 【element-plus】全局组件类型提示
 * 体验相当丝滑 😋 
 */
import {
  ElAffix,
  ElAlert,
  ElAutocomplete,
  ElAvatar,
  ElBacktop,
  ElBadge,
  ElBreadcrumb,
  ElButton,
  ElCalendar,
  ElCard,
  ElCarousel,
  ElCascader,
  ElCascaderPanel,
  ElCheckTag,
  ElCheckbox,
  ElCol,
  ElCollapse,
  ElCollapseTransition,
  ElColorPicker,
  ElConfigProvider,
  ElContainer,
  ElCountdown,
  ElDatePicker,
  ElDescriptions,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElEmpty,
  ElForm,
  ElIcon,
  ElImage,
  ElImageViewer,
  ElInput,
  ElInputNumber,
  ElLink,
  ElMenu,
  ElOverlay,
  ElPageHeader,
  ElPagination,
  ElPopconfirm,
  ElPopper,
  ElProgress,
  ElRadio,
  ElRate,
  ElResult,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElSelectV2,
  ElSkeleton,
  ElSlider,
  ElSpace,
  ElStatistic,
  ElSteps,
  ElSwitch,
  ElTable,
  ElTableV2,
  ElTabs,
  ElTag,
  ElText,
  ElTimePicker,
  ElTimeSelect,
  ElTimeline,
  ElTooltip,
  ElTransfer,
  ElTree,
  ElTreeSelect,
  ElTreeV2,
  ElUpload,
  ElVirtualList,
  ElWatermark,
  ElInfiniteScroll,
  ElLoading,
  ElMessage,
  ElMessageBox,
  ElNotification,
  ElPopover,
} from 'element-plus'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAffix: typeof ElAffix,
    ElAlert: typeof ElAlert,
    ElAutocomplete: typeof ElAutocomplete,
    ElAvatar: typeof ElAvatar,
    ElBacktop: typeof ElBacktop,
    ElBadge: typeof ElBadge,
    ElBreadcrumb: typeof ElBreadcrumb,
    ElButton: typeof ElButton,
    ElCalendar: typeof ElCalendar,
    ElCard: typeof ElCard,
    ElCarousel: typeof ElCarousel,
    ElCascader: typeof ElCascader,
    ElCascaderPanel: typeof ElCascaderPanel,
    ElCheckTag: typeof ElCheckTag,
    ElCheckbox: typeof ElCheckbox,
    ElCol: typeof ElCol,
    ElCollapse: typeof ElCollapse,
    ElCollapseTransition: typeof ElCollapseTransition,
    ElColorPicker: typeof ElColorPicker,
    ElConfigProvider: typeof ElConfigProvider,
    ElContainer: typeof ElContainer,
    ElCountdown: typeof ElCountdown,
    ElDatePicker: typeof ElDatePicker,
    ElDescriptions: typeof ElDescriptions,
    ElDialog: typeof ElDialog,
    ElDivider: typeof ElDivider,
    ElDrawer: typeof ElDrawer,
    ElDropdown: typeof ElDropdown,
    ElEmpty: typeof ElEmpty,
    ElForm: typeof ElForm,
    ElIcon: typeof ElIcon,
    ElImage: typeof ElImage,
    ElImageViewer: typeof ElImageViewer,
    ElInput: typeof ElInput,
    ElInputNumber: typeof ElInputNumber,
    ElLink: typeof ElLink,
    ElMenu: typeof ElMenu,
    ElOverlay: typeof ElOverlay,
    ElPageHeader: typeof ElPageHeader,
    ElPagination: typeof ElPagination,
    ElPopconfirm: typeof ElPopconfirm,
    ElPopper: typeof ElPopper,
    ElProgress: typeof ElProgress,
    ElRadio: typeof ElRadio,
    ElRate: typeof ElRate,
    ElResult: typeof ElResult,
    ElRow: typeof ElRow,
    ElScrollbar: typeof ElScrollbar,
    ElSelect: typeof ElSelect,
    ElSelectV2: typeof ElSelectV2,
    ElSkeleton: typeof ElSkeleton,
    ElSlider: typeof ElSlider,
    ElSpace: typeof ElSpace,
    ElStatistic: typeof ElStatistic,
    ElSteps: typeof ElSteps,
    ElSwitch: typeof ElSwitch,
    ElTable: typeof ElTable,
    ElTableV2: typeof ElTableV2,
    ElTabs: typeof ElTabs,
    ElTag: typeof ElTag,
    ElText: typeof ElText,
    ElTimePicker: typeof ElTimePicker,
    ElTimeSelect: typeof ElTimeSelect,
    ElTimeline: typeof ElTimeline,
    ElTooltip: typeof ElTooltip,
    ElTransfer: typeof ElTransfer,
    ElTree: typeof ElTree,
    ElTreeSelect: typeof ElTreeSelect,
    ElTreeV2: typeof ElTreeV2,
    ElUpload: typeof ElUpload,
    ElVirtualList: typeof ElVirtualList,
    ElWatermark: typeof ElWatermark,
    ElInfiniteScroll: typeof ElInfiniteScroll,
    ElLoading: typeof ElLoading,
    ElMessage: typeof ElMessage,
    ElMessageBox: typeof ElMessageBox,
    ElNotification: typeof ElNotification,
    ElPopover: typeof ElPopover
  }
}